### ISSUE TITLE
aws 0.36.0 plugin broken

### ISSUE THREAD

**Issue by jzendle** [turbot/steampipe-plugin-sdk#236]
**Describe the bug**

select v.cidr_block from aws_vpc v join aws_ec2_instance i on i.vpc_id = v.vpc_id where i.instance_id = 'i-0367b6705f9078c25'

gives rpc error:

Warning: executeQueries: query 1 of 1 failed: pq: rpc error: code = Internal desc = 'Get' call requires an '=' qual for column:'instance_id' operator: =

**Steampipe version (`steampipe -v`)**
v0.84.0

aws plugin v0.36.0

**Comment by kaidaguerre** [comment]
@jzendle apologies for taking so long to resolve this. 

I have identified a bug in the plugin sdk causing this issue, which I have fixed. So the aws plugin should reflect this change once it has gone through it's release cycle
