### ISSUE TITLE
Logger not printing message with newline character `\n` correctly

### ISSUE THREAD

**Issue by LalitLab** [turbot/steampipe-plugin-sdk#283]
There is an issue with the Steampipe logger while printing messages with newline charater `\n`

For instance:
```plugin.Logger(ctx).Error("snowflake_user.DescribeUser", "TEST.error", "SQL access control error:\nInsufficient privileges to operate on user 'SNOWFLAKE'")``` prints only part prior to `\n` in the log

```
2022-03-04 12:00:25.723 UTC [ERROR] steampipe-plugin-snowflake.plugin: [ERROR] snowflake_user.DescribeUser: TEST.error="SQL access control error:
```

**Comment by binaek** [comment]
The original solution of sending back log messages as JSON is not viable since `hclog` adds it's own parameters which are not present in the `LINE` format (namely `@module`).
