### ISSUE TITLE
Support streaming list results

### ISSUE THREAD

**Issue by japborst** [turbot/steampipe-plugin-sdk#341]
Created upon request from https://github.com/turbot/steampipe-plugin-github/pull/167.

Next to `d.streamListItem` it would be great to have a `d.streamList` functionality when multiple items need to be streamed.

A naive implementation could look something like:

```golang
func (d *QueryData) streamList(ctx context.Context, item interface{}) {
	  for _, item := range item {
		  if item != "" {
			  d.StreamListItem(ctx, item)
		  }
	  
		  // Context can be cancelled due to manual cancellation or the limit has been hit
		  if d.QueryStatus.RowsRemaining(ctx) == 0 {
			  break
		  }
	  }
}
```

**Comment by kaidaguerre** [comment]
Hi @japborst . Sorry for taking a while to respond to this one.

So as I understand it, this would just be a shortcut function to stream multiple items with once sdk call?

**Comment by japborst** [comment]
@kaidaguerre thanks for taking a look.

That's indeed correct.

**Comment by kaidaguerre** [comment]
@japborst got an even simpler solution for this - `StreamListItem` will be updated to being a variadic function:

```
func (d *QueryData) streamListItem(ctx context.Context, items ...interface{}) 
```
so to pass an array of items you just need to expand it:
```
d.StreamListItem(ctx, rows...)
```

This will be in the upcoming v4.0.0 sdk release
