### ISSUE TITLE
Steampipe CLI remains in `Loading results` state when executing queries involving the Get API call

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe-plugin-sdk#382]
Steampipe plugin SDK version: v4.0.1
Steampipe CLI version: v0.16.0-rc.11

The get API calls do not seem to work with the latest SDK version (v4.0.1).

When I execute the following query the CLI seems to be getting stuck at the loading results phase -
 `select * from aws_ec2_instance where instance_id = 'i-0237b7320d201234'`
After pressing Ctrl+C  I get an `Error: execution cancelled` which is expected. When I execute the query once again the results are rendered correctly (however intermittently).

AWS plugin branch: [sdk_v4](https://github.com/turbot/steampipe-plugin-aws/pull/1194)

**Comment by cbruno10** [comment]
I've observed the same behaviour with Steampipe SDK v4.0.1 and Steampipe CLI v0.17.0-alpha.6 and v0.16.0-alpha.11 in the AWS and GitHub plugins. In particular, any time key columns are passed in such that a `GetConfig` would be called, the query hangs and never finishes or returns successful results.

For instance, the following queries did not succeed for me:
- `select * from aws_ec2_instance where instance_id = 'i-0e3103bcdfe5b3246';`
- `select instance_id, image_id from aws_ec2_instance where instance_id = 'i-0e3103bcdfe5b3246';`
- `select * from github_team where organization = 'turbot' and slug = 'test-team';`

Notably though, queries without any quals, and queries calling a `ListConfig` with or without key columns all succeeded.
