### ISSUE TITLE
Improve support for GetItemMatrixFunc

### ISSUE THREAD

**Issue by dihedron** [turbot/steampipe-plugin-sdk#481]
I am developing a plugin to query OpenStack APIs via Steampipe (see [here](https://github.com/dihedron/steampipe-plugin-openstack)). **I would like the user to interact with multiple installations of OpenStack at once, even within the same query** so that when a certain installation is specified in the query, the plugin can collect the proper set of credentials, API endpoints etc. and perform the appropriate calls.
This requires the configuration schema to support more complex data structures than it currently does. I would like to have a configuration that under the "regions" parmeter has a *list of maps*:
```json
{
   ... whatever ...
   "regions": [
        {
            "api_endpoint": "https://my_region_1/api/v1...",
            "api_key": "my_api_key_for_region_1",
            "api_secret": "my_api_secret_for_region_1"
        },
        {
            "api_endpoint": "https://my_region_2/api/v1...",
            "api_key": "my_api_key_for_region_2",
            "api_secret": "my_api_secret_for_region_2"
        },
        ... whatever ....
    ],
    ... whatever ....
}
```
This would allow the plugin to retrieve the proper entry from the `regions` list and use the values to connect to the API, based on the query contents. I have written a few Terraform providers and AFAICT there does not seem to be any problem in mixing Lists and Maps in HCLv2 configuration. The current implementation does not support TypeMap as a data type in configuration.
As an alternative, it would be nice if it were possible to configure multiple instances of the same plugin under different connection names so you can run:

```sql
select vm.id, vm.name from openstack_region_1;  // connect to region_1 based on region1.spc
select vm.id, vm.name from openstack_region_2;  // connect to region_2 based on region2.spc
```

I tried it but but I could not find instructions on how to do it and it does not seem to work.

**Comment by dihedron** [comment]
Cool, I'll try it tomorrow as soon as I turn on my PC. This looks exactly like what I was looking for.

**Comment by e-gineer** [comment]
Great. To expand a bit further:
* Each connection generally represents a single unit of credentials (account, installation, etc)
* Connections are grouped with aggregators.
* AWS Account is a good example of this unit.

In some cases, we want to do queries / gather data across multiple sources within a single connection. For example, a single AWS account has EC2 Instances in 16 regions. In this case, we support a "matrix" to fan out the hydration across many different calls and consolidate it into a single table in a single connection - https://pkg.go.dev/github.com/turbot/steampipe-plugin-sdk/v5/plugin#MatrixItemMapFunc

I think your use case calls for a connection per installation combined with aggregators, but wanted to call out the "matrix" capability too in case it's inspirational for future situations.

**Comment by dihedron** [comment]
Thanks a lot @e-gineer I tried your suggestion and it works like a charm!

Thanks for the clarification, I see I was bending the "matrix" feature to a different use case and it would not fit properly in the big schema of things. Your suggestion addresses my problem perfectly.

This was the only major feature that I thought was lacking in my plugin and I'm glad there is nothing to do there. At this point I will be adding tables one at a time. If you're interested in taking ownership sometime and could spend a minute in reviewing if the work done so far complies with your guidelines, please consider doing so and opening issues.

**Comment by e-gineer** [comment]
Awesome @dihedron :rocket:

We have a [plugin release checklist](https://steampipe.io/docs/develop/plugin-release-checklist) and @misraved will definitely reach out to give feedback on https://github.com/dihedron/steampipe-plugin-openstack as well!

**Comment by kaidaguerre** [comment]
glad you got this resolved @dihedron 
Closing
