### ISSUE TITLE
ColumnType_DATETIME deprecation should suggest the replacement field

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe-plugin-sdk#9]
As per https://github.com/golang/go/wiki/Deprecated it would be useful if the deprecation also suggested the replacement field, which I believe to be `ColumnType_TIMESTAMP`?

https://github.com/turbot/steampipe-plugin-sdk/blob/cdf6f8e6655057434accde9f307553db5e6819ed/grpc/proto/plugin.pb.go#L89-L90

**Comment by kaidaguerre** [comment]
```Deprecated: ColumnType_DATETIME is deprecated. Instead, use ColumnType_TIMESTAMP```
